services:
  - type: web
    name: ema-crossover-bot
    runtime: python
    plan: free
    buildCommand: |-
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |-
      python3 bot.py